# Fichier de référence : Export des logs Suricata vers ELK via TCP

# Objet 1 : Source (Lecture locale du fichier généré par Suricata)
source src_suricata {
  wildcard-file(
    base-dir("/var/log/suricata")
    filename-pattern("eve.json")
    recursive(yes)
    follow-freq(1)
    program-override("suricata")
    flags(no-parse)
  );
};

# Objet 2 : Destination (Envoi vers le SIEM en TCP)
destination dst_logstash {
  network(
    "192.168.30.10"
    port(5000)
    transport("tcp")
    template("$MSG\n") # Crucial : expédie le JSON pur sans enveloppe syslog
  );
};

# Objet 3 : Routage (Log Path)
log {
  source(src_suricata); 
  destination(dst_logstash);
};