services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"   
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - soc-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - soc-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5044:5044"       # Filebeat
      - "5000:5000"   # Suricata (via pfSense, TCP via syslog-ng)
    volumes:
      - ./ingestion/logstash/pipelines:/usr/share/logstash/pipeline:ro
      - ./ingestion/logstash/dictionaries:/usr/share/logstash/dictionaries:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - soc-net
  backend-api:
    build: ./backend-api
    container_name: backend-api
    restart: unless-stopped
    volumes:
      - ./ml/models:/app/models:ro
    ports:
      - "8001:8000"
    networks:
      - soc-net

  risk-scoring-engine:
    build: ./risk-scoring-engine
    container_name: risk-scoring-engine
    restart: unless-stopped
    ports:
      - "8002:8000"
    networks:
      - soc-net

  correlation-engine:
    build: ./correlation-engine
    container_name: correlation-engine
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ML_API=http://backend-api:8000
      - RISK_API=http://risk-scoring-engine:8000
    depends_on:
      elasticsearch:
        condition: service_healthy
      backend-api:
        condition: service_started
    restart: unless-stopped
    networks:
      - soc-net
  reporting-engine:
    build: ./reporting
    container_name: reporting-engine
    environment:
      - ES_HOST=http://elasticsearch:9200
    volumes:
      - ./reporting/output:/app/output
    ports:
      - "8003:8000"
    networks:
      - soc-net

volumes:
  esdata:

networks:
  soc-net: