input {
  beats {
    port => 5044
  }
  udp {
    port  => 5000
    type  => "suricata"
  }
}

filter {
  if [type] == "suricata" {
    # On tente d'extraire la partie JSON du log syslog de pfSense
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} suricata(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:json_payload}" }
    }
    
    # Si le grok échoue (ce n'est pas un log Suricata, ex: un log DHCP ou Firewall normal), on le supprime
    if "_grokparsefailure" in [tags] {
      drop { }
    } else if [json_payload] {
      # Si c'est bien du Suricata, on parse le JSON
      json {
        source => "json_payload"
        remove_field => ["message", "json_payload", "syslog_timestamp", "syslog_hostname", "syslog_pid"]
      }
    }
  }
}

output {
  if [type] == "suricata" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "suricata-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "filebeat-%{+YYYY.MM.dd}"
    }
  }
  stdout { codec => rubydebug }   # à retirer une fois le pipeline validé
}