input {
  beats {
    port => 5044
  }
  tcp {
    port  => 5000
    codec => json_lines
    type  => "suricata"
  }
}

filter {
  if [type] == "suricata" and [event_type] == "alert" {
    
    # 1. Le dictionnaire a besoin que le SID soit une chaîne de caractères (string)
    mutate {
      convert => { "[alert][signature_id]" => "string" }
    }

    # 2. Le plugin translate cherche le SID dans le fichier YAML
    # ATTENTION: Assure-toi que le chemin dictionary_path correspond au chemin interne dans ton conteneur Docker !
    translate {
      field => "[alert][signature_id]"
      destination => "[@metadata][mitre_json]"
      dictionary_path => "/usr/share/logstash/pipeline/mitre_mapping.yml" 
      fallback => '{"tactic": "Unassigned", "tactic_id": "None", "technique": "Unassigned", "technique_id": "None"}'
    }

    # 3. On parse le JSON retourné par le dictionnaire pour créer le sous-champ "mitre"
    json {
      source => "[@metadata][mitre_json]"
      target => "mitre"
    }
  }
}

output {
  if [type] == "suricata" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "suricata-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "filebeat-%{+YYYY.MM.dd}"
    }
  }
  stdout { codec => rubydebug }   # à retirer une fois le pipeline validé
}