input {
  udp {
    port => 5000
    codec => json
  }

  beats {
    port => 5044
  }
}

filter {
  # tu peux enrichir plus tard (geoip, parsing, etc.)
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "suricata-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}