input {
  udp {
    port => 5000
    codec => json
  }

  beats {
    port => 5044
  }
}

filter {
   # logs système linux (Filebeat)
  if [fileset][module] == "system" {
    mutate { add_tag => ["system-log"] }
  }

  # logs Suricata
  if "suricata" in [tags] {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "suricata-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}